---
- hosts: localhost
  vars:
    devtools: "{{ ansible_env.DEVTOOLS | bool }}"
  roles:
    - { role: apache }
    - { role: mariadb }
    - { role: php }
    - { role: redis }
    - { role: asdf, when: devtools }
    - { role: asdf-direnv, when: devtools }
    - { role: asdf-nodejs, when: devtools }
    - { role: asdf-tmux, when: devtools }
    - { role: bash-completion, when: devtools }
    - { role: bash-source-dir, when: devtools }
    - { role: docker, when: devtools }
    - { role: git, when: devtools }
    - { role: htop, when: devtools }
    - { role: jq, when: devtools }
    - { role: nano, when: devtools }
    - { role: tree, when: devtools }
    - { role: vim, when: devtools }
