---
- name: create service conf directory
  file: path="{{ mariadb_service_conf_dir }}" state=directory

- name: create service conf
  copy: src=initdb dest="{{ mariadb_service_conf_dir }}"

- block:
  - name: create volume
    docker_volume: name="{{ mariadb_volume_name }}" state=present

  - name: start :{{ mariadb_version }}
    docker_container:
      name: mariadb
      image: mariadb:{{ mariadb_version }}
      env:
        MYSQL_ROOT_PASSWORD: "{{ mariadb_root_pass | string }}"
      volumes:
        - "{{ mariadb_service_conf_dir }}/initdb:/docker-entrypoint-initdb.d"
        - "{{ mariadb_volume_name }}:/var/lib/mysql"
      ports:
      - "{{ mariadb_host_port }}:3306"
      comparisons:
        image: strict
        env: strict
        volumes: allow_more_present

  - name: install repo
    copy: src=MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo

  - name: install client
    yum: name=MariaDB-client state=present

  - name: configure mysql connection protocol
    copy: src=mysql-protocol.cnf dest=/etc/my.cnf.d
  become: yes
