---
- block:
  - name: install apache and mod_ssl
    yum: name="{{ packages }}" state=present
    vars:
      packages:
        - httpd
        - mod_ssl

  - name: start service
    service: name=httpd state=started enabled=yes
  become: yes
