---
- name: install php with extensions
  yum: name="{{ packages }}" state=present enablerepo=remi-php74
  notify:
    - restart apache
  vars:
    packages:
      - php
      - php-cli
      - php-common
      - php-gd
      - php-json
      - php-intl
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-xml
      - php-zip
  become: yes
