---
- set_fact:
    php_remi_version: "{{ php_version | regex_replace('\\.') }}"

- name: install :{{ php_version }} with extensions
  yum: name="{{ packages }}" state=present enablerepo=remi-php{{ php_remi_version }}
  notify:
    - restart apache
  vars:
    packages:
      - php
      - php-cli
      - php-common
      - php-gd
      - php-json
      - php-intl
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-xml
      - php-zip
  become: yes
