---
- name: create bash source dirictory
  file: path="{{ bash_source_dir_path }}" state=directory

- name: create autosource script
  copy: src=.bashinit dest="{{ bash_source_dir_path }}"

- name: source autosource in bashrc
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    state: present
    line: "[[ -f '{{ bash_source_dir_path }}/.bashinit' ]] && source '{{ bash_source_dir_path }}/.bashinit'"
