---
- block:
  - name: install completion
    get_url:
      url: https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux
      dest: "{{ tmux_completion_dir }}/tmux.sh"
      mode: 0644

  - name: create common configs
    copy: src=tmux.conf.configs dest="{{ tmux_global_confdir }}"

  - name: install plugin manager
    git:
      repo: "{{ tmux_tpm_repo_url }}"
      dest: "{{ tmux_tpm_install_dir }}"

  - name: create plugins config
    template: src=tmux.conf.plugins dest="{{ tmux_global_confdir }}"
    notify:
      - tmux install plugins

  - name: load global configs to tmux.conf
    lineinfile:
      path: "{{ tmux_global_confdir }}/tmux.conf"
      line: source-file {{ tmux_global_confdir }}/{{ item }}
      create: yes
    with_items:
      - tmux.conf.configs
      - tmux.conf.plugins

  become: yes
  become_user: root
