---
- name: install build dependencies
  yum: name="{{ packages }}" state=present
  vars:
    packages:
    - "@Development tools"
    - ncurses-devel
  become: yes

- block:
  - name: "install plugin"
    command: "bash -lc 'asdf plugin-add tmux'"
    args:
      creates: "{{ asdf_dir }}/plugins/tmux"

  - name: "install tmux:{{ tmux_version }}"
    command: "bash -lc 'asdf install tmux {{ tmux_version }}'"
    args:
      creates: "{{ asdf_dir }}/installs/tmux/{{ tmux_version }}"

  - name: "set tmux:{{ tmux_version }} global"
    template: src=tmux.sh dest="{{ tmux_bash_hook_dir }}"

  - name: install tmux completion
    get_url:
      url: https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux
      dest: "{{ tmux_completion_dir }}/tmux.sh"
      mode: 0644
  become: yes
  become_user: root
