---
- block:
  - name: install build dependencies
    yum: name="@Development tools" state=present

  - name: install runtime dependencies
    yum: name="{{ packages }}" state=present
    vars:
      packages:
        - ncurses-devel
        - libevent

  - name: install plugin
    command: "bash -lc 'asdf plugin-add tmux'"
    args:
      creates: "{{ asdf_dir }}/plugins/tmux"

  - name: install version {{ tmux_version }}
    command: "bash -lc 'asdf install tmux {{ tmux_version }}'"
    args:
      creates: "{{ asdf_dir }}/installs/tmux/{{ tmux_version }}"

  - name: set version {{ tmux_version }} global
    template: src=tmux.sh dest="{{ tmux_bash_hook_dir }}"

  - name: install completion
    get_url:
      url: https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux
      dest: "{{ tmux_completion_dir }}/tmux.sh"
      mode: 0644

  - name: create global configs
    copy: src=tmux.conf.configs dest="{{ tmux_global_confdir }}"

  - name: load global configs to tmux.conf
    lineinfile:
      path: "{{ tmux_global_confdir }}/tmux.conf"
      line: source-file {{ tmux_global_confdir }}/{{ item }}
      create: yes
    with_items:
      - tmux.conf.configs
  become: yes
  become_user: root

- name: install plugin manager
  git:
    repo: "{{ tmux_tpm_repo_url }}"
    dest: "{{ tmux_tpm_install_dir }}"

- name: create user plugins configs
  template: src=tmux.conf.plugins dest="{{ tmux_user_confdir }}/.tmux.conf.plugins"

- name: load user configs to tmux.conf
  lineinfile:
    path: "{{ tmux_user_confdir }}/.tmux.conf"
    line: source-file {{ tmux_user_confdir }}/{{ item }}
    create: yes
  with_items:
    - .tmux.conf.plugins

- name: install plugins
  command: "bash -lc '{{ tmux_tpm_install_dir }}/scripts/install_plugins.sh'"
  changed_when: no
