---
- block:
  - name: install build dependencies
    yum: name="@Development tools" state=present

  - name: install runtime dependencies
    yum: name="{{ packages }}" state=present
    vars:
      packages:
        - ncurses-devel
        - libevent

  - name: install plugin
    command: "bash -lc 'asdf plugin-add tmux'"
    args:
      creates: "{{ asdf_dir }}/plugins/tmux"

  - name: install :{{ tmux_version }}
    command: "bash -lc 'asdf install tmux {{ tmux_version }}'"
    args:
      creates: "{{ asdf_dir }}/installs/tmux/{{ tmux_version }}"

  - name: set :{{ tmux_version }} global
    template: src=tmux.sh dest="{{ tmux_bash_hook_dir }}"

  - name: install completion
    get_url:
      url: https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux
      dest: "{{ tmux_completion_dir }}/tmux.sh"
      mode: 0644

  - name: create common configs
    copy: src=tmux.conf.configs dest="{{ tmux_global_confdir }}"

  - name: install plugin manager
    git:
      repo: "{{ tmux_tpm_repo_url }}"
      dest: "{{ tmux_tpm_install_dir }}"

  - name: create plugins config
    template: src=tmux.conf.plugins dest="{{ tmux_global_confdir }}"
    notify:
      - tmux install plugins

  - name: load global configs to tmux.conf
    lineinfile:
      path: "{{ tmux_global_confdir }}/tmux.conf"
      line: source-file {{ tmux_global_confdir }}/{{ item }}
      create: yes
    with_items:
      - tmux.conf.configs
      - tmux.conf.plugins
  become: yes
  become_user: root
